batch_size: [128, 512]
d_model: [64, 128]
num_heads: [2, 4]
num_layers: [2, 4]
clustering_method: ["KMEDOIDS", "AGGLOMERATIVE"]
clustering_param:
  KMEDOIDS: [1000, 2500, 5000]
  AGGLOMERATIVE: [5, 7.5, 10, 12.5, 15] #check
clustering_metric: ["euclidean"]
