name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Ensure submodules are fetched as well
          submodules: 'true'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Python tests
        run: |
          pytest tests/

      - name: Install C++ dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build g++

      - name: Configure CMake
        run: |
          cmake -S OSTC -B OSTC/Debug -DDebug=1 -GNinja

      - name: Build C++ tests
        run: |
          ninja -C OSTC/Debug

      - name: Run C++ tests with CTest
        run: |
          GTEST_COLOR=1 ctest --test-dir OSTC/Debug --output-on-failure -V
